bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

imprint_store/imprint_store/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

imprint_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from imprint_store.views import handler404

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('wishlist/', include('wishlist.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = handler404

wishlist/urls.py
from django.urls import path
from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.view_wishlist, name='view_wishlist'),
    path(
        'add/<int:product_id>/',
        views.add_to_wishlist,
        name='add_to_wishlist'),
    path(
        'remove/<int:product_id>/',
        views.remove_from_wishlist,
        name='remove_from_wishlist'),
]

wishlist/models.py
from django.db import models
from django.contrib.auth.models import User
from products.models import Product


class Wishlist(models.Model):
    """ Wishlist model """
    user = models.OneToOneField(
        User, on_delete=models.CASCADE,
        related_name='wishlist')

    products = models.ManyToManyField(Product, blank=True)

    def __str__(self):
        return f"{self.user.username}'s wishlist"

wishlist/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from products.models import Product
from .models import Wishlist


@login_required
def add_to_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist, created = Wishlist.objects.get_or_create(user=request.user)
    wishlist.products.add(product)
    return redirect('wishlist:view_wishlist')


@login_required
def remove_from_wishlist(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    wishlist, created = Wishlist.objects.get_or_create(user=request.user)
    wishlist.products.remove(product)
    return redirect('wishlist:view_wishlist')


@login_required
def view_wishlist(request):
    wishlist, created = Wishlist.objects.get_or_create(user=request.user)
    return render(request, 'wishlist/view_wishlist.html', {
        'wishlist': wishlist})

wishlist/templates/wishlist/view_wishlist.html
{% extends 'base.html' %}

{% block page_header %}
    <div class="container my-4">
        <h2>{{ user.username }}'s Wishlist</h2>
    </div>
{% endblock %}

{% block content %}
    <div class="container my-4">
        <ul class="list-group">
            {% for product in wishlist.products.all %}
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    {{ product.name }}
                    <a href="{% url 'wishlist:remove_from_wishlist' product.id %}" class="btn btn-danger btn-sm">Remove</a>
                </li>
            {% empty %}
                <li class="list-group-item">Your wishlist is empty.</li>
            {% endfor %}
        </ul>
        <div class="mt-4">
            <a href="{% url 'products' %}" class="btn btn-primary">Back to Shop</a>
        </div>
    </div>
{% endblock %}